name: alert-server CI

on:
#  pull_request:
#    branches: [ "main" ]
  push:
    branches: [ "main" ]

env:
  SERVICE_NAME: flip-sync-be

  BLUE_PORT: 48122
  GREEN_PORT: 38122
  INNER_PORT: 8080
  TIME_DELATE: 300



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check out another private repo (same org)
        uses: actions/checkout@v3
        with:
          repository: flip-sync/flip-sync-be-yml
          path: flip-sync-server/src/main/resources
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew ${{ env.SERVICE_NAME }}:build --no-daemon
        shell: bash

      - name: Log in to Docker Hub
        run: |
          echo "${{ github.DOCKER_TOKEN }}" | docker login -u ${{ github.DOCKER_USERNAME }} --password-stdin
        shell: bash

      - name: Build and push Docker image
        run: |
          docker build -t ${{ github.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:local ./${{ env.SERVICE_NAME }}
          
          docker tag ${{ github.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:local ${{ github.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.run_number }}
          docker tag ${{ github.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:local ${{ github.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:latest
          
          docker push ${{ github.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.run_number }}
          docker push ${{ github.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:latest
          
          docker image rm ${{ github.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:local
          docker image rm ${{ github.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.run_number }}
          docker image rm ${{ github.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:latest
        shell: bash

      - name: Deploy to Server
        run: |
          set -e
          
          # rsa 키 생성
          # github secrets에 등록된 key를 .ssh/id_rsa에 저장
          
          echo "${{ github.SERVER_PRICATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ github.SERVER_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub
          
          
          # known_hosts 파일에 내용 추가 (서버의 공개키 등록)
          ssh-keyscan -H ${{ github.SERVER_IP }} >> ~/.ssh/known_hosts
          
          # PROJECT_DIR 정의
          PROJECT_DIR=/home/${{ github.SERVER_USERNAME }}/docker/${{ env.SERVICE_NAME }}
          
          # 서버에 디렉토리 생성 및 권한 설정
          ssh ${{ github.SERVER_USERNAME }}@${{ github.SERVER_IP }} "sudo mkdir -p $PROJECT_DIR && sudo chmod -R 755 $PROJECT_DIR"
          
          # 소유권 변경
          ssh ${{ github.SERVER_USERNAME }}@${{ github.SERVER_IP }} "sudo chown -R ${{ github.SERVER_USERNAME }}:${{ github.SERVER_USERNAME }} $PROJECT_DIR"
          
          # deploy.sh 파일 전송
          scp ./deploy.sh ${{ github.SERVER_USERNAME }}@${{ github.SERVER_IP }}:$PROJECT_DIR
          
          # deploy.sh 실행
          ssh -T ${{ github.SERVER_USERNAME }}@${{ github.SERVER_IP }} "set -e; sudo bash $PROJECT_DIR/deploy.sh ${{ env.SERVICE_NAME }} $PROJECT_DIR '${{ env.BLUE_PORT }}' '${{ env.GREEN_PORT }}' '${{ env.INNER_PORT }}' '${{ env.TIME_DELATE }}' '${{ github.DOCKER_USERNAME }}' '${{ github.DOCKER_TOKEN }}' '${{ github.NGINX_DOMAIN }}' ''"
        shell: bash